# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - Arm_controller
    - Flippers_controller

  Arm_controller:
    type: FollowJointTrajectory
    joints:
      - RoveCore_Joint1
      - ArmBase_Revolute-51
      - ArmSectionA_Joint3
      - ArmSectionB_Joint4
      - ArmSectionC_Joint5
      - ArmSectionD_Joint6
  Flippers_controller:
    type: FollowJointTrajectory
    joints:
      - RoveCore_FlipperBLJoint
      - RoveCore_FlipperBRJoint
      - RoveCore_FlipperFLJoint
      - RoveCore_FlipperFRJoint